### PR TITLE
fix(evaluateModule): strip shebang comment

### LINKED ISSUE #8: Hashbang comments should be allowed in Modules
Since `import()` from a module code can load a file with script code, but the target is resolved into a module record, it's possible to load a script that is also used as a command.

**Steps to reproduce**
In `make-importer`, replace `moddir/index.js` with:
```js
#!/usr/bin/env node
```

Then execute:
```sh
$ node -r esm test/test-moddir.js 
```
Actual result:
```
$ node  -r esm test/test-moddir.js 
TAP version 13
# moddir index.js
not ok 1 unexpected exception
  ---
    operator: notEqual
    expected: |-
      { [SyntaxError: Unexpected character '#' (1:125)] pos: 125, loc: { line: 1, column: 125 } }
    actual: |-
      { [SyntaxError: Unexpected character '#' (1:125)] pos: 125, loc: { line: 1, column: 125 } }
    at: Test.<anonymous> (~/projects/make-importer/test/test-moddir.js:56:7)
    stack: |-
      SyntaxError: Unexpected character '#' (1:125)
          at Parser.raise (~/projects/make-importer/node_modules/@agoric/default-evaluate-options/dist/default-evaluate-options.cjs.js:6974:17)
          at Parser.readToken_numberSign (~/projects/make-importer/node_modules/@agoric/default-evaluate-options/dist/default-evaluate-options.cjs.js:7372:12)
```
Expected result, same as node's native import:
```sh
$ node -r esm test/moddir/index.js
// no error
```

### LINKED ISSUE #45: Hashbang comments should be allowed in Modules
Since `import()` from a module code can load a file with script code, but the target is resolved into a module record, it's possible to load a script that is also used as a command.

**Steps to reproduce**
In `make-importer`, replace `moddir/index.js` with:
```js
#!/usr/bin/env node
```

Then execute:
```sh
$ node -r esm test/test-moddir.js 
```
Actual result:
```
$ node  -r esm test/test-moddir.js 
TAP version 13
# moddir index.js
not ok 1 unexpected exception
  ---
    operator: notEqual
    expected: |-
      { [SyntaxError: Unexpected character '#' (1:125)] pos: 125, loc: { line: 1, column: 125 } }
    actual: |-
      { [SyntaxError: Unexpected character '#' (1:125)] pos: 125, loc: { line: 1, column: 125 } }
    at: Test.<anonymous> (~/projects/make-importer/test/test-moddir.js:56:7)
    stack: |-
      SyntaxError: Unexpected character '#' (1:125)
          at Parser.raise (~/projects/make-importer/node_modules/@agoric/default-evaluate-options/dist/default-evaluate-options.cjs.js:6974:17)
          at Parser.readToken_numberSign (~/projects/make-importer/node_modules/@agoric/default-evaluate-options/dist/default-evaluate-options.cjs.js:7372:12)
```
Expected result, same as node's native import:
```sh
$ node -r esm test/moddir/index.js
// no error
```

### PR DESCRIPTION
**Pull request by michaelfig**
Module sources should ignore the shebang comment, not copy it into the
resulting functor where it causes a syntax error.

Closes #8

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -101,7 +101,10 @@ const makeModuleTransformer = (babelCore, importer) => {
       importSources: {},
       importDecls: [],
     };
-    const scriptSource = transformSource(moduleSource, sourceOptions);
+    const noShebangModuleSource = moduleSource.startsWith('#!')
+      ? `//${moduleSource}`
+      : moduleSource;
+    const scriptSource = transformSource(noShebangModuleSource, sourceOptions);
```
Comment (jfparadis) [inline src/index.js]: Maybe avoid a ternary operator?
